# Generated by Django 5.0.3 on 2024-03-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosync', '0004_customuser_created_at'),
        ('featurs', '0012_wastetransfer_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='featurs.role'),
        ),
    ]
