# Generated by Django 5.0.4 on 2024-05-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Billing / Oill Allocation', 'verbose_name_plural': 'Billings / Oill Allocations'},
        ),
        migrations.AddField(
            model_name='dumpingentryrecord',
            name='Distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dumpingentryrecord',
            name='SecondaryTransferStation',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='waste_management.secondarytransferstation'),
        ),
        migrations.DeleteModel(
            name='OilAllocation',
        ),
    ]
