# Generated by Django 5.0.4 on 2024-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_alter_billing_options_dumpingentryrecord_distance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dumpingentryrecord',
            options={'verbose_name': 'Dumping Entry / Oill Allocation(Billing)', 'verbose_name_plural': 'Dumping Entrys / Oill Allocations (Billings)'},
        ),
        migrations.AlterField(
            model_name='dumpingentryrecord',
            name='TimeOfArrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpingentryrecord',
            name='TimeOfDeparture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
