# Generated by Django 5.0.6 on 2024-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0003_secondarytransferstation_fine_for_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarytransferstation',
            name='collection_hours',
            field=models.CharField(default='08:00-17:00', max_length=100),
        ),
    ]
