# Generated by Django 5.0.4 on 2024-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_remove_manager_id_alter_manager_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
