# Generated by Django 5.0.6 on 2024-05-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_management', '0002_alter_secondarytransferstation_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contract_id', models.CharField(max_length=50, unique=True)),
                ('reg_id', models.CharField(max_length=50)),
                ('reg_date', models.DateField()),
                ('tin', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('workforce_size', models.PositiveIntegerField()),
                ('payment_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_duration', models.DurationField()),
                ('area_of_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_contractors', to='waste_management.area')),
                ('designated_sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sts_contractors', to='waste_management.area')),
            ],
        ),
    ]
