# Generated by Django 5.0.6 on 2024-05-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
        ('waste_management', '0002_alter_secondarytransferstation_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartycontractor',
            name='designated_sts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sts_contractors', to='waste_management.secondarytransferstation'),
        ),
    ]
