# Generated by Django 5.0.6 on 2024-05-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_employee_loggedworkinghours_wastecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedworkinghours',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loggedworkinghours',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loggedworkinghours',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='thirdpartycontractor',
            name='reg_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='waste_type',
            field=models.CharField(choices=[('domestic', 'Domestic Waste'), ('plastic', 'Plastic Waste'), ('construction', 'Construction Waste')], max_length=100),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deficit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_waste', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor.thirdpartycontractor')),
            ],
        ),
    ]
