# Generated by Django 5.0.6 on 2024-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_alter_loggedworkinghours_logout_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='deficit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
