# Generated by Django 5.0.6 on 2024-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_alter_billing_basic_pay_alter_billing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
