# Generated by Django 4.2.11 on 2024-03-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProfile',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('LastLogin', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('LandfillID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.commonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('PermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTransferStation',
            fields=[
                ('STSID', models.AutoField(primary_key=True, serialize=False)),
                ('WardNumber', models.CharField(max_length=20)),
                ('Capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GPSLatitude', models.FloatField()),
                ('GPSLongitude', models.FloatField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.commonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('RegistrationNumber', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Open Truck', 'Open Truck'), ('Dump Truck', 'Dump Truck'), ('Compactor', 'Compactor'), ('Container Carrier', 'Container Carrier')], max_length=255)),
                ('Capacity', models.DecimalField(choices=[(3, '3 ton'), (5, '5 ton'), (7, '7 ton')], decimal_places=2, max_digits=5)),
                ('FuelCostLoaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FuelCostUnloaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransfer',
            fields=[
                ('TransferID', models.AutoField(primary_key=True, serialize=False)),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOfArrival', models.DateTimeField()),
                ('TimeOfDeparture', models.DateTimeField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfer', to='featurs.landfill')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfer', to='featurs.secondarytransferstation')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteID', models.AutoField(primary_key=True, serialize=False)),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstimatedTime', models.DurationField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_route', to='featurs.landfill')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_route', to='featurs.secondarytransferstation')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('RolePermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.permission')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.role')),
            ],
        ),
        migrations.CreateModel(
            name='OilAllocation',
            fields=[
                ('AllocationID', models.AutoField(primary_key=True, serialize=False)),
                ('WeekNumber', models.IntegerField()),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OilAllocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DumpingEntryRecord',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOfArrival', models.DateTimeField()),
                ('TimeOfDeparture', models.DateTimeField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.landfill')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='commonprofile',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.role'),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('WeekNumber', models.IntegerField()),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OilConsumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
    ]
