# Generated by Django 5.0.4 on 2024-05-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('RegistrationNumber', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Open Truck', 'Open Truck'), ('Dump Truck', 'Dump Truck'), ('Compactor', 'Compactor'), ('Container Carrier', 'Container Carrier')], max_length=255)),
                ('Capacity', models.IntegerField(choices=[(3, '3 ton'), (5, '5 ton'), (7, '7 ton'), (15, '15 ton')])),
                ('FuelCostLoaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FuelCostUnloaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('LandfillID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=255)),
                ('Capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OperationalTimespan', models.CharField(default='24/7', max_length=100)),
                ('Latitude', models.FloatField(default=0.0)),
                ('Longitude', models.FloatField(default=0.0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTransferStation',
            fields=[
                ('STSID', models.AutoField(primary_key=True, serialize=False)),
                ('WardNumber', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=255)),
                ('Capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Latitude', models.FloatField(default=0.0)),
                ('Longitude', models.FloatField(default=0.0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OilAllocation',
            fields=[
                ('AllocationID', models.AutoField(primary_key=True, serialize=False)),
                ('WeekNumber', models.IntegerField()),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OilAllocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DumpingEntryRecord',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOfArrival', models.DateTimeField()),
                ('TimeOfDeparture', models.DateTimeField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.landfill')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('WeekNumber', models.IntegerField()),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VolumeOfWaste')),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransfer',
            fields=[
                ('TransferID', models.AutoField(primary_key=True, serialize=False)),
                ('Distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VolumeOfWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOfArrival', models.DateTimeField()),
                ('TimeOfDeparture', models.DateTimeField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfer', to='featurs.landfill')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfer', to='featurs.secondarytransferstation')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.vehicle')),
            ],
        ),
    ]
