# Generated by Django 5.0.4 on 2024-05-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfill',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='secondarytransferstation',
            name='Manager',
        ),
    ]
