# Generated by Django 4.2.11 on 2024-03-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0002_alter_landfill_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='OilAllocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='featurs.oilallocation'),
        ),
    ]
