# Generated by Django 4.2.11 on 2024-03-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0004_landfill_capacity_landfill_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
