# Generated by Django 4.2.11 on 2024-03-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featurs', '0007_remove_billing_oilconsumed_remove_billing_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='VolumeOfWaste',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VolumeOfWaste'),
        ),
        migrations.CreateModel(
            name='STSManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.secondarytransferstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandfillManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featurs.landfill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
