# Generated by Django 4.2.11 on 2024-03-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0008_alter_billing_volumeofwaste_stsmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfill',
            name='Capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
