# Generated by Django 4.2.11 on 2024-03-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0010_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
