# Generated by Django 4.2.11 on 2024-05-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0012_wastetransfer_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfill',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='secondarytransferstation',
            name='Manager',
        ),
    ]
