# Generated by Django 4.2.11 on 2024-05-03 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featurs', '0018_alter_stsmanager_sts_alter_stsmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfillmanager',
            name='landfill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='featurs.landfill'),
        ),
        migrations.AlterField(
            model_name='landfillmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
