# Generated by Django 4.2.11 on 2024-05-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0019_alter_landfillmanager_landfill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarytransferstation',
            name='Location',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
