# Generated by Django 4.2.11 on 2024-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0020_secondarytransferstation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarytransferstation',
            name='Location',
            field=models.CharField(max_length=255),
        ),
    ]
