# Generated by Django 4.2.11 on 2024-05-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featurs', '0023_alter_landfillmanager_landfill_alter_stsmanager_sts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfillmanager',
            name='landfill',
        ),
        migrations.RemoveField(
            model_name='stsmanager',
            name='sts',
        ),
        migrations.AddField(
            model_name='landfill',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='featurs.landfillmanager'),
        ),
        migrations.AddField(
            model_name='secondarytransferstation',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='featurs.stsmanager'),
        ),
        migrations.AlterField(
            model_name='landfillmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stsmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
