# Generated by Django 4.2.11 on 2024-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurs', '0024_remove_landfillmanager_landfill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarytransferstation',
            name='GPSLatitude',
        ),
        migrations.RemoveField(
            model_name='secondarytransferstation',
            name='GPSLongitude',
        ),
        migrations.AddField(
            model_name='secondarytransferstation',
            name='Latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='secondarytransferstation',
            name='Longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
