# Generated by Django 4.2.11 on 2024-05-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featurs', '0026_remove_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stsmanager',
            name='user',
        ),
        migrations.AlterField(
            model_name='landfill',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secondarytransferstation',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LandfillManager',
        ),
        migrations.DeleteModel(
            name='STSManager',
        ),
    ]
