# Generated by Django 5.0.6 on 2024-05-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_engagement', '0001_initial'),
        ('waste_management', '0004_secondarytransferstation_collection_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='sts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waste_management.secondarytransferstation'),
        ),
    ]
